name: utmsafe
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  intl: ^0.17.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.5.0
  fl_chart: ^0.69.2
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/loginpic.png
    - assets/utmsafelogo.png
  uses-material-design: true
