// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4DbiSSJNRRGSgTE_mCnGrnMv3jUBXyPc',
    appId: '1:1013666372928:web:a20b5b4b9b06f70084eea5',
    messagingSenderId: '1013666372928',
    projectId: 'utmsafe-9825c',
    authDomain: 'utmsafe-9825c.firebaseapp.com',
    storageBucket: 'utmsafe-9825c.firebasestorage.app',
    measurementId: 'G-Y2G3EHVLXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK_-a66ym9X8cOcOSx0I0TkfbIUPRRcEM',
    appId: '1:1013666372928:android:a98e52173c11b53884eea5',
    messagingSenderId: '1013666372928',
    projectId: 'utmsafe-9825c',
    storageBucket: 'utmsafe-9825c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkAizZc0_LfxsZF1280V9w1NRp0LAbiNU',
    appId: '1:1013666372928:ios:651282afb1142b7084eea5',
    messagingSenderId: '1013666372928',
    projectId: 'utmsafe-9825c',
    storageBucket: 'utmsafe-9825c.firebasestorage.app',
    iosBundleId: 'com.guardians.utmsafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkAizZc0_LfxsZF1280V9w1NRp0LAbiNU',
    appId: '1:1013666372928:ios:651282afb1142b7084eea5',
    messagingSenderId: '1013666372928',
    projectId: 'utmsafe-9825c',
    storageBucket: 'utmsafe-9825c.firebasestorage.app',
    iosBundleId: 'com.guardians.utmsafe',
  );
}
